### ISSUE TITLE
May we get more examples relates to use IMC API?

### ISSUE THREAD

**Issue by moonlovestar** [Tree-of-Savior-Addon-Community/Addon-Tutorial#1]
Hi Authors,

  I want to develop add-ons but I cannot find some tutorials, examples and documents for API.
  I see some add-ons codes(e.g., fpsincreaser, expcard viewer and calculator, betterquest and so on). There are many function calls that I cannot see definition in the code.
  I think it is API provided by IMC, but where can I find these API and know which API can I use?

Thanks,
Moonlove

**Comment by WillTheDoggy** [comment]
Trial and error. Examining the IPF files in the treeofsavior folder. Many things are pretty self-explanatory when you relate it to what it means in game. You just need experience with the game. Nothing is documented.

This a tutorial you can read:
https://github.com/Tree-of-Savior-Addon-Community/Addon-Tutorial/wiki

**Comment by Xanaxiel** [comment]
Ayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by WillTheDoggy** [comment]
`ONE()` AYYYYYYYYYYYYYYYYYYYYYYYYYYYYY LMAO

**Comment by BlaXun** [comment]
Any news on this? Did anybody maybe collect a list of commands we can use? Thanks in advance!

**Comment by Miei** [comment]
If you dump the global table you can view all of the defined functions

**Comment by BlaXun** [comment]
Thx Miei,

So how would I do this? Would I have to simply decrypt the ipf-files and look for commands in there? Sorry for beeinf a noob on this topic... I really want to get into it and I am aIT-Specialist for program development for iOS... so once i get the start done I know I can contribute to the community... I just have to get over the first few hurdles

**Comment by Miei** [comment]
Well, you can do that, yes, you can find a lot of interesting things that way. Plus, you can see the actual function definitions, so that's nice.

However, I was talking about iterating the [global table](https://www.lua.org/pil/14.html), `_G`, and printing each function name. These are basically the two ways that I found information about ToS lua code in the past.

You can do so with a simple for-loop or with a library such as  [inspect.lua](https://github.com/kikito/inspect.lua) that will create some output with a slightly nicer format.

**Comment by BlaXun** [comment]
Woah, thank you Miei.

This is exactly what I was looking for :)
Thanks for helping me out ...the ToS Community is pretty toxic...its great to have people like u around that care to help.

Thx!

**Comment by BlaXun** [comment]
Wohoo! Its just a small step, but I managed to output my characters invested STAT-Points onto System-Chat and Public Chat. 

But I've run into a small problem now.
I found the function MAKE_GAUGE_BALLOON ...and the last argument takes a string to use different styles to show a bubble (its that countdown bar) ...how would I find out what styles are avialable? 

Thanks in advance :)
Havin so much fun right now...just might need a hint from time to time.

And, are there any important things I need to know? Like functions you will ALWAYS need?

**Comment by BlaXun** [comment]
Miei, how would I get the output of the inspect lua saved? Can I use lua to write the result into a textfile or something?

**Comment by Miei** [comment]
Writing to a file is not specific to lua in ToS, I really think you should google things like that, you'll find your answers much faster. 

I don't know much about `MAKE_GAUGE_BALLOON`, I'm not doing any programming for ToS at the moment because I haven't played in months. I'd say you can check for places that this function is used or check the .xml file that corresponds to the lua file that it is defined in, if there is one. You'll find those by decrypting the .ipf files.

**Comment by BlaXun** [comment]
Goddammit... yeah, no idea what was writing yesterday...it seems I was just a little bit too excited ;)
I got my lecture ready now and I'll start by checking other peoples addons. I think I can stop bothering u now. But, just so u know, it seems u are one of the very few people that actually share knowledge when it comes to the ToS Dev Community...it really is a shame

**Comment by BlaXun** [comment]
I am really getting the hang of this.
I managed to dump all functions and am now starting to rip functions of classes... however, is there a way to read function-definitions? I'd really like to know what kind of arguments the functions need ...I am trying with reflection...but can't really get it to work...I mean, I got stuff like this:

{
  GetAngle = <function 1>,
  GetBuff = <function 2>,
  GetBuffByName = <function 3>,
  GetBuffCount = <function 4>,
  GetBuffIndexed = <function 5>,
  GetCID = <function 6>,
  GetDestPosAngle = <function 7>,
  GetDestPosDistance = <function 8>,
  GetDialogInfo = <function 9>,
  GetDistance = <function 10>,
  GetFamilyName = <function 11>,
  GetGender = <function 12>,
  GetIcon = <function 13>,
  GetJob = <function 14>,
  GetLevel = <function 15>,
  GetMonRankbyHandle = <function 16>,
  GetMonsterClassName = <function 17>,
  GetMyPcBuff = <function 18>,
  GetName = <function 19>,
  GetOwner = <function 20>,
  GetPCName = <function 21>,
  GetPositionInMap = <function 22>,
  GetPositionInScreen = <function 23>,
  GetPositionInUI = <function 24>,
  GetSDR = <function 25>,
  GetStanceName = <function 26>,
  GetStat = <function 27>,
  GetTargetInfo = <function 28>,
  GetTeamID = <function 29>,
  GetWorldPosByMinimapPos = <function 30>,
  IsMonster = <function 31>,	//	Prüft ob der angegebene Handle (arg0) ein Monster ist
  IsNegativeRelation = <function 32>,
  IsPC = <function 33> //	Prüft ob der angegebene Handle (arg0) ein Player Character ist
}

But i have no Idea bout the arguments it takes :D

**Comment by Miei** [comment]
Not that I know of, if it is defined by the client instead of in the ipf files, then I would do a search of all of the extracted ipf files to find where/how it is used.

**Comment by BlaXun** [comment]
Hello Miei,

I wanted to ask i u ever did show your own frame.
I am trying to get this done by checking out the developerconsole addon.

As far as I understand I define the frame in XML, bind some functions (open and close) and should then
be able to show the frame within the game...however, my frame is always nil.... 

Are XML files ignored unless they are inside a IPF?

**Comment by Miei** [comment]
Yes, they are ignored unless they are inside an IPF.

**Comment by BlaXun** [comment]
So you cant really test your UI unless u package it up in an ipf... thats a shame..

**Comment by kenshiniu** [comment]
Hello guys!
Bumped on this issue when I was looking for tos addon  development resources

Thanks @wuaw for your helping, I've got a better hanging on lua global table concept `_G` tahnks to you!

Due to the dev console addon being limited on screen, I've exported all ` _G` functions on a file, hope this helps someone!
[_Gfunctions.txt](https://github.com/Tree-of-Savior-Addon-Community/Addon-Tutorial/files/1202324/_Gfunctions.txt)

I'll try to search for them on the `ipf` file to provide some type of documentation, thanks again!
